### ISSUE TITLE
Tighten up targeted pages/permissions?

### ISSUE THREAD

**Issue by jbeda** [jacobsee/Gitosoft#1]
I want to install it but it looks like it isn't restricted to just github.com!

**Comment by jacobsee** [comment]
Ack, you would be correct about that! Updated version with only permission "Read and change your data on github.com" is publishing to the Chrome store now!

**Comment by jbeda** [comment]
Hmm -- still seeing it ask for everything.  Not sure if there is latency in publishing updates.
![screen shot 2018-06-07 at 1 46 26 pm](https://user-images.githubusercontent.com/37310/41125458-5a0389fc-6a59-11e8-9d37-80d07d2c6af6.png)

**Comment by jacobsee** [comment]
Yes, I still have "Publishing in progress" on the new one. Will comment back shortly when it looks like it's up.

**Comment by jacobsee** [comment]
Okay, it looks published on my end. As long as you see version 0.0.3 and not 0.0.2, it requests more targeted permissions! 
![screen shot 2018-06-07 at 1 03 33 pm](https://user-images.githubusercontent.com/5027680/41126243-59323376-6a53-11e8-964a-dfe6b255847d.png)

**Comment by jacobsee** [comment]
But please let me know if you spot anything else that should be improved (besides logos and issue #2, which I know of). This is my first stab at a Chrome extension - very unfamiliar and trying to learn.

**Comment by jbeda** [comment]
Works for me! Thanks!
